### PR TITLE
Test user

### PR DESCRIPTION
**Pull request by thainda-0252**
## Related Tickets
[- ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/69557?issue_count=43&issue_position=1&next_issue_id=69401)

## WHAT (optional)
- Viết test case cho user

## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Comment by vinh-nd2002** [comment]
Ok

**Comment by thainda-0252** [comment]
ready

**Comment by thainda-0252** [comment]
ready

**Comment by thainda-0252** [comment]
ready

**Pull request merged**
